### ISSUE TITLE
Fails to load with Scalafmt 1.5.1

### ISSUE THREAD

**Issue by onzo-vlamp** [lucidsoftware/neo-sbt-scalafmt#69]
Plugin works with 1.4, but using `scalafmtVersion := "1.5.1"` I get:

```
[error] java.lang.NoSuchMethodError: org.scalafmt.config.ScalafmtConfig.copy$default$23()Ljava/lang/String;
[error] 	at com.lucidchart.scalafmt.impl.Scalafmtter$$anon$1.<init>(Scalafmtter.scala:16)
[error] 	at com.lucidchart.scalafmt.impl.Scalafmtter.formatter(Scalafmtter.scala:14)
[error] 	at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$.$anonfun$scalafmtFn$1(ScalafmtCorePlugin.scala:59)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (sbt:scalafmt::scalafmt) java.lang.NoSuchMethodError: org.scalafmt.config.ScalafmtConfig.copy$default$23()Ljava/lang/String;
```

**Comment by dwijnand** [comment]
Reported upstream: https://github.com/scalameta/scalafmt/issues/1158.

**Comment by olafurpg** [comment]
The org.scalafmt.config package is not public API, neo-sbt-scalafmt should follow the recommendations I made here https://github.com/lucidsoftware/neo-sbt-scalafmt/pull/36#issuecomment-321938150 
to use the following methods
https://github.com/scalameta/scalafmt/blob/4a5b7681933fa1a1c289d5fa5aa8a4abfe8a71c9/scalafmt-core/shared/src/main/scala/org/scalafmt/Scalafmt.scala#L77-L89

**Comment by jubecker** [comment]
I created a fix for this https://github.com/lucidsoftware/neo-sbt-scalafmt/pull/72 . Comments, ideas?
Would love to get this in shape.

**Comment by mwz** [comment]
Would it be possible to get the above PR merged and released?
