### PR TITLE
Cross-build to Scalafmt 1.2, fix bincompat issue with Scalafmt 1.5

### LINKED ISSUE #69: Fails to load with Scalafmt 1.5.1
Plugin works with 1.4, but using `scalafmtVersion := "1.5.1"` I get:

```
[error] java.lang.NoSuchMethodError: org.scalafmt.config.ScalafmtConfig.copy$default$23()Ljava/lang/String;
[error] 	at com.lucidchart.scalafmt.impl.Scalafmtter$$anon$1.<init>(Scalafmtter.scala:16)
[error] 	at com.lucidchart.scalafmt.impl.Scalafmtter.formatter(Scalafmtter.scala:14)
[error] 	at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$.$anonfun$scalafmtFn$1(ScalafmtCorePlugin.scala:59)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (sbt:scalafmt::scalafmt) java.lang.NoSuchMethodError: org.scalafmt.config.ScalafmtConfig.copy$default$23()Ljava/lang/String;
```

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #69

### CODE REVIEW

**Comment by dwijnand** [comment]
Uh, this way looks even harder, because I don't know sbt-cross that well. Going back to #70.
